[build]
  command = "node scripts/writeConf.js && jekyll build"
  publish = "_site"

[context.production]
  command = "node scripts/writeConf.js && jekyll build --config _config_production.yml"

[context.deploy-preview.environment]
  command = "node scripts/writeConf.js && jekyll build"