[build]
  command = "node scripts/writeConf.js && jekyll build --config"
  publish = "_site"

[context.production]
  command = "node scripts/writeConf.js && jekyll build --config _config_production.yml"

[context.deploy-preview]
  command = "node scripts/writeConf.js && jekyll build --config _config.yml"
  publish = "_site"